export enum ErrorCode {
  // Validation Errors
  VALIDATION_ERROR = "VALIDATION_ERROR",
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",
  INVALID_FORMAT = "INVALID_FORMAT",
  INVALID_INPUT = 'INVALID_INPUT',
  INVALID_ID = 'INVALID_ID',
     
  // Authentication & Authorization Errors
  UNAUTHORIZED = "UNAUTHORIZED",
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  FORBIDDEN = "FORBIDDEN",
  AUTO_LOGIN_FAILED = "AUTO_LOGIN_FAILED",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
     
  // Resource Not Found Errors
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  AD_NOT_FOUND = "AD_NOT_FOUND",
  ADS_PACKAGE_NOT_FOUND = "ADS_PACKAGE_NOT_FOUND",
  BLOG_NOT_FOUND = "BLOG_NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  PHOTO_NOT_FOUND = "PHOTO_NOT_FOUND",
  NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND",
  SEO_NOT_FOUND = "SEO_NOT_FOUND",
  PIXEL_NOT_FOUND = "PIXEL_NOT_FOUND",
  BAD_REQUEST = "BAD_REQUEST",
     
  // User-specific Errors
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_NOT_VERIFIED = "USER_NOT_VERIFIED",
  USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED",
     
  // OTP-specific Errors
  INVALID_OTP = "INVALID_OTP",
  OTP_EXPIRED = "OTP_EXPIRED",
  OTP_SEND_FAILED = "OTP_SEND_FAILED",
  OTP_VERIFICATION_FAILED = "OTP_VERIFICATION_FAILED",
     
  // Conflict Errors
  DUPLICATE_ENTRY = "DUPLICATE_ENTRY",
  CONFLICT = "CONFLICT",

  // Blog-specific Errors
  BLOG_TITLE_EXISTS = "BLOG_TITLE_EXISTS",
  BLOG_PERMISSION_DENIED = "BLOG_PERMISSION_DENIED",
  BLOG_UNPUBLISHED_LIKE = "BLOG_UNPUBLISHED_LIKE",
  BLOG_UPDATE_FAILED = "BLOG_UPDATE_FAILED",
  BLOG_DELETE_FAILED = "BLOG_DELETE_FAILED",
  BLOG_CREATE_FAILED = "BLOG_CREATE_FAILED",
  BLOG_FETCH_FAILED = "BLOG_FETCH_FAILED",
     
  // Client Request Errors
  PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE",
  UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
     
  // Server & Database Errors
  EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  DATABASE_ERROR = "DATABASE_ERROR",
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  TIMEOUT_ERROR = "TIMEOUT_ERROR",
  SERVER_ERROR = "SERVER_ERROR",
  FAILED_TO_SEND_EMAIL = "FAILED_TO_SEND_EMAIL",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
     
  // General Errors
  UNKNOWN_ERROR = 'UNKNOWN_ERROR'
}