export enum ErrorCode {
  // Validation Errors
  VALIDATION_ERROR = "VALIDATION_ERROR",
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",
  INVALID_FORMAT = "INVALID_FORMAT",
  INVALID_INPUT = 'INVALID_INPUT',
  INVALID_ID = 'INVALID_ID',
  
  // Authentication & Authorization Errors
  UNAUTHORIZED = "UNAUTHORIZED",
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  FORBIDDEN = "FORBIDDEN",
  AUTO_LOGIN_FAILED = "AUTO_LOGIN_FAILED",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  
  // Resource Not Found Errors
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  POST_NOT_FOUND = "POST_NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  
  // Conflict Errors
  DUPLICATE_ENTRY = "DUPLICATE_ENTRY",
  CONFLICT = "CONFLICT",
  
  // Client Request Errors
  PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE",
  UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  
  // Server & Database Errors
  EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  DATABASE_ERROR = "DATABASE_ERROR",
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  TIMEOUT_ERROR = "TIMEOUT_ERROR",
  SERVER_ERROR = "SERVER_ERROR",
  FAILED_TO_SEND_EMAIL = "FAILED_TO_SEND_EMAIL",
  
  // General Errors
  UNKNOWN_ERROR = 'UNKNOWN_ERROR'
}