---
deployment:
  tasks:
    - export DEPLOYPATH=/home/octopusad/expressapp
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH/
    - cd $DEPLOYPATH
    - npm install
    - npm run build
    - npm prune --production