export enum NotificationType {
  // Ad notifications
  AD_APPROVED = "AD_APPROVED",
  AD_REJECTED = "AD_REJECTED",
  AD_ACTIVATED = "AD_ACTIVATED",
  AD_DEACTIVATED = "AD_DEACTIVATED",

  // Ad crud
  AD_CREATED = "AD_CREATED",
  AD_MODIFIED = "AD_MODIFIED",
  AD_DELETED = "AD_DELETED",

  // Ad photo
  AD_PHOTO_ADDED = "AD_PHOTO_ADDED",
  AD_PHOTO_UPDATED = "AD_PHOTO_UPDATED",
  AD_PHOTO_DELETED = "AD_PHOTO_DELETED",

  // Ad promotion
  AD_PROMOTED = "AD_PROMOTED",
  AD_DEPROMOTED = "AD_DEPROMOTED",

  // Payment notifications
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  PAYMENT_PENDING = "PAYMENT_PENDING",
  PAYMENT_REFUNDED = "PAYMENT_REFUNDED",

  // Credit notifications
  CREDIT_ADDED = "CREDIT_ADDED",
  CREDIT_DEDUCTED = "CREDIT_DEDUCTED",
  CREDIT_LOW_BALANCE = "CREDIT_LOW_BALANCE",
  ADMIN_BROADCAST = "ADMIN_BROADCAST",
}
