name: Deploy to Contabo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        nSMUMEyWkpzY2JZ2

      - name: Deploy via SSH (Password auth)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.VNC_PASSWORD }}
          script: |
            # Go to your app folder
            cd /root/marketing-platform

            # Pull latest code
            git pull origin main

            # Build & restart containers
            docker compose down
            docker compose up -d --build

            # Optional: clean old images
            docker image prune -f
